### ISSUE TITLE
HMMsearch

### ISSUE THREAD

**Issue by jchambe5** [pjlmac/Bioinfo-Group-Project-ND#2]
All HMMSearch results are coming back with zero hits 

not sure if the translation code results or the hmmsearch code is the issue

**Comment by pjlmac** [comment]
Did switching the *amino.fasta to *protein.fasta solve the problem?

**Comment by jchambe5** [comment]
nope

**Comment by pjlmac** [comment]
Okay, stand by...

**Comment by pjlmac** [comment]
I don't know what's going on with the translation code. When I pop open the output file in a normal text editor, it looks fine.

**Comment by pjlmac** [comment]
I ran one of the amino acid sequences 
(>Obese1
PDPTASPESLPDSVGQAGMQQAGLTLMAVAVCVAFQTSEAILPMASSCCTEVSHHVSGRLLERVSSCSIQRADGDCDLAAVILHVKRRRICISPHNRTLKQWMRASEVKKNGRENVCSGKKQPSRKDRKGHTTRKHRTRGTHRHEASR) through blast and it comes up with C-C motif chemokine 28 from mouse.

**Comment by pjlmac** [comment]
I also tried two amino acids in one blast search online
(>Control1
EDTVLWIPWTMDGGQPVPSPLVPLGNGSDYSMSLEQKTTFVFVILLFIFLGILIVRCFRILLDPYRSMPTSTWADGLEGLEKGQFDHALA)

and

(>Control1
PDPTASPESLPDSVGQAGMQQAGLTLMAVAVCVAFQTSEAILPMASSCCTEVSHHVSGRLLERVSSCSIQRADGDCDLAAVILHVKRRRICISPHNRTLKQWMRASEVKKNGRENVCSGKKQPSRKDRKGHTTRKHRTRGTHRHEASR)

I'm getting cortexin-3 for the first one and the C-C motif chemokine 28 from mouse for the second.

However, Blast can't process three or more sequences like this at once. I'm going to try altering the seq names (so that the sequences submitted have unique ID lines) and see if that does the trick.

**Comment by pjlmac** [comment]
Huh, that was not the problem. Reverting the names back to the same name does not throw an error message on Blast anymore. I don't think the problem is with the translation program, but I could be wrong.

**Comment by jchambe5** [comment]
i tried putting all the files in the same repo so I didnt have to add any pathway nonsense in the hmmsearch code/loop and it didn't come back with any hits there either so still no fix

**Comment by pjlmac** [comment]
So I did find out why there are repeat protein sequences in the output translation sequence file. It is because the source nucleotide fasta file does have repeat DNA sequences (makes sense, if we are going to figure out frequency of mRNA/DNA sequences in the experiment).

**Comment by pjlmac** [comment]
Hey Joe, I'll upload a fasta file with protein sequences that I know work on NCBI BLAST. Can you try those?

**Comment by jchambe5** [comment]
yep

**Comment by jchambe5** [comment]
have you looked over the hmm search and build code to see if that looks right? I'm pretty sure it is because it is fairly simple but do I have something out of order?

**Comment by pjlmac** [comment]
I'll take a look at the code in one sec. I'm pushing a file called testForJoe.fasta

**Comment by pjlmac** [comment]
There ya go. I'll dig through the HMM code to see if that works. The two protein sequences definitely do match to proteins in the BLAST archive.

**Comment by pjlmac** [comment]
No, I know what the problem is, though I am unsure how to fix it. The code that I wrote only looks at the first occurrence of a start codon. As such, it doesn't find the relevant amino acid sequences that you have programmed in (though it did find a handful of them). If anyone can help fix this, I would greatly appreciate it! I'll keep on plugging away on my end to see what is up and, if possible, I can scrap this code in favor of a different one that works.

**Comment by ayamasaki2011** [comment]
From what I'm gleaning from looking at the code, it seems like it'll just start at the beginning of a sequence line and start translating - it doesn't seem like there's anything in there that looks for a start codon at all. This could be what's causing the issue, as the first start codon's going to define the open reading frame for the rest of the sequence.

At one point, was there not a section that looked for a start codon? There's also a segment of my cobbled-together code that does the same thing - I'll paste it here:

start=line.find('ATG')
sequencestart=line[start:]

Essentially trimming off the first bits of the sequence until you hit the first start codon. Not sure what the appropriate variable designation is for "line" in your code here, but this might help sort out the ORF issue?

**Comment by pjlmac** [comment]
Find wasn't working when I tried this, hence the radically different code.

**Comment by jchambe5** [comment]
find has not worked for me either

**Comment by ayamasaki2011** [comment]
Fair enough, but I think the problem still stands that there needs to be some way to establish an ORF.

Since you're already storing the current codon in a variable, is it possible to check it against the start codon with a while loop? Something along the lines of:

while res != 'ATG':
       break

Before moving on to the actual translation part of the code?

Actually, I think this may have to be done before the loop that progresses through the characters in groups of 3, simply because we don't know that the start codon is going to be in-frame with regards to the start of the sequence. So there may have to be an additional loop that starts at the front of the line, scans character by character until it finds A,T,G in order, and then moves into the next part of the translation code.

**Comment by pjlmac** [comment]
Hey Amanda, your "almost" code from a few commits ago looks like it was close. Any idea what the error message was?

**Comment by pjlmac** [comment]
I pushed a code that works on other folks' websites. I've been in the process of plugging it into our particular project, but I have to run for a bit.

**Comment by pjlmac** [comment]
The filename is called testTranslation.py

**Comment by ayamasaki2011** [comment]
Not @ my computer at the moment, so I can't quite look back at which version you're talking about, but the major issue I was having was how to pass the current codon as a reference to the codon dictionary to call the corresponding amino acid. I kept getting errors that the program was expecting a string, but was receiving either a list or a number. I couldn't quite figure out where the code was storing the value of the 3-letter string to pass along.

**Comment by pjlmac** [comment]
Kristi put together a code called DNAtoProtein.py that works!
